version: '3.8'

services:
  # --- INFRAESTRUTURA ---
  postgres:
    image: postgis/postgis:16-3.4
    container_name: mudex-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mudex_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mudex_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mudex-redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mudex-rabbitmq

  # --- MICROSERVIÇOS ---
  api-gateway:
    build:
      context: ./api-gateway
    container_name: mudex-api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    environment:
      - USER_SERVICE_URL=http://mudex-user-service:3001

  user-service:
    build:
      context: ./user-service
    container_name: mudex-user-service
    ports:
      - "3001:3000"  # Mapeamos a 3001 para fora, mas ele roda na 3000 dentro
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@mudex-postgres:5432/mudex_db
